server:
  port: 9091
spring:
  application:
    name: springCloudProjectProvider  # 服务名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jfsstu?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

eureka:
  client:
    register-with-eureka: true # 是否将自己注册到Eureka Server，默认为true
    service-url: # Eureka Server地址
      defaultZone: http://eureka9080.com:9080/eureka/,http://eureka9082.com:9082/eureka/,http://eureka9083.com:9083/eureka/  # Eureka Server地址
  instance:
    instance-id: spring-cloud-fist-provider-8001  # 自定义服务实例名称
    prefer-ip-address: true # 是否优先使用IP来作为主机名

# Spring Boot 2.50对 actuator 监控屏蔽了大多数的节点，只暴露了 heath 节点，本段配置（*）就是为了开启所有的节点
management:
  endpoints:
    web:
      exposure:
        include: "*"   # * 在yaml 文件属于关键字，所以需要加引号
info:
  app.name: micro-service-cloud-provider-dept
  company.name: c.biancheng.net
  build.aetifactId: @project.artifactId@
  build.version: @project.version@

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: jfs.study.**.entity
  configuration:
    #默认开启驼峰命名法，可以不用设置该属性
    map-underscore-to-camel-case: true